
name: Publish Package
on:
  release:
    types: [published]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - run: rm -f README.md
      - run: rm -f README.RU.md
      - run: mv NPM-README.md README.md
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@flowXM'
          always-auth: true
      - run: yarn
      - run: yarn publish ./projects/angular-yandex-smart-captcha
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
